### ISSUE TITLE
Handling of TCP connection errors by HTTPClient

### ISSUE THREAD

**Issue by smason** [ponylang/http#15]
I've just started with Pony and found that the `HTTPClient` doesn't deliver connection errors back to the caller.  I can see the code should be making it to [`_ClientConnection._connect_failed`](https://github.com/ponylang/ponyc/blob/9c912eee7b75b6924f389db9e2d8a7942bc80370/packages/net/http/_client_connection.pony#L137) but things stop propagating pretty soon after that.

I see there's a comment saying `TODO send fail response` in the `_cancel_all` method, and was wondering if anybody was looking at/fixing this?

My guess would be to put something into the [`HandlerFactory`](https://github.com/ponylang/ponyc/blob/07763fa168439217adadf00f0f939bf4488af165/packages/net/http/http_handler.pony#L93) but am new so thought I should ask for suggestions first!

Thanks, and hope that all makes sense!

**Comment by SeanTAllen** [comment]
@mfelsche thoughts?

**Comment by SeanTAllen** [comment]
@smason how about opening a PR to get feedback on your change?

**Comment by mfelsche** [comment]
The client HTTPHandlers are now notified of closed connections (if `keepalive_timeout` is specified), ssl auth failures and failed connect. Server HTTPHandlers are now notified of closed connections (if `keepalive_timeout` is specified). It is not exactly like your solution @smason, which is also liked. The code merged with #20 was motivated by some other users feedback. It seems i've totally overlooked this issue, sorry for this. My bad! 

will close this issue nonetheless. Feel free to reopen or create a new one, if the current error handling/reporting needs sth.
