### ISSUE TITLE
HTTPClient doesn't close the connection after receiving chunked data

### ISSUE THREAD

**Issue by aturley** [ponylang/http#21]
## Steps to reproduce

I wrote a program to demonstrate this issue. It uses the GitHub API.

NOTE:

* You must replace the string `YOUR_GITHUB_PERSONAL_AUTH_TOKEN_HERE` with your own GitHub [personal access token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line).
* You must include the `http` library using `stable`: `stable add github ponylang/http`
* You must build with `stable`: `stable env ponyc`
* The first (and only) argument should be the name of a repo, like `ponylang/ponyc`.

```
use "http"
use "net/ssl"

actor Main
  new create(env: Env) =>
    let auth_token = "YOUR_GITHUB_PERSONAL_AUTH_TOKEN_HERE"

    let sslctx = try
      recover val
        SSLContext
          .>set_client_verify(true)
          .>set_authority(None)?
        end
      end

    let repo = try
      env.args(1)?
    else
      env.err.print("first argument must be the name of a repo")
      env.exitcode(-1)
      return
    end

    try
      let auth = env.root as AmbientAuth
      let client = HTTPClient(auth, sslctx)
      let nf = recover val NotifyFactory(env.out) end

      let url_string = "https://api.github.com/repos/" + repo + "/issues"

      env.out.print("getting data at " + url_string)

      let url = URL.valid(url_string)?

      let req = Payload.request("GET", url)
      req("User-Agent") = "Pony httpget"

      req("Authorization") = "token " + auth_token

      let sentreq = client(consume req, nf)?
    end


class NotifyFactory is HandlerFactory
  let _os: OutStream

  new create(os: OutStream) =>
    _os = os

  fun apply(session: HTTPSession): HTTPHandler ref^ =>
    Notify(_os)

class Notify is HTTPHandler
  let _os: OutStream

  new create(os: OutStream) =>
    _os = os

  fun ref apply(response: Payload val) =>
    _os.print("received response")

  fun ref chunk(data: ByteSeq) =>
    _os.print("received chunk")

  fun ref finished() =>
    _os.print("finished chunks")

  fun failed(reason: HTTPFailureReason) =>
    _os.print("failed")
```

If you pass a valid repo with lots of issues that should cause GitHub to send the response using chunked encoding, which will trigger the issue and the program will not terminate. If you pass an invalid repo name then the response will be short and GitHub will not use chunked encoding, so the program will terminate.

## Expected Behavior

When the program is finished receiving chunked data the HTTPClient will close the connection and terminate.

## Actual Behavior

The connection is kept open. As a consequence, the program does not terminate.

**Comment by aturley** [comment]
I believe the issue is [in _client_connection.pony](https://github.com/ponylang/http/blob/master/http/_client_connection.pony#L193).

```
  be _finish() =>
    """
    Indicates that the last *inbound* body chunk has been sent to
    `_chunk`. This is passed on to the front end.
    _send_pending is called to detect that _unsent and _sent are emptye
    and that _conn can be disposed.
    """
    _app_handler.finished()
    _send_pending()
```

This behavior is called when the client finishes handling chunked data for a request, but it does not remove the request from the `_sent` queue. `_send_pending()` checks to make sure that `_sent` is empty, and if it is it closes the connection, but since the item is not removed from the `_sent` queue the queue is never empty so the connection is never closed.

On the other hand, `be _deliver(response: Payload val)` is called when an unchunked response is received, and it removes the current request from `_sent`. I believe that this is the correct behavior and the library should do the same thing when it is finished receiving chunked data for a request.

I've tested this by adding a line to `_finish()` that removes the request from the queue and it seems to work, but I haven't tested it extensively.

```
  be _finish() =>
    """
    Indicates that the last *inbound* body chunk has been sent to
    `_chunk`. This is passed on to the front end.

    _send_pending is called to detect that _unsent and _sent are emptye
    and that _conn can be disposed.
    """
      let request = _sent.shift()?
      _app_handler.finished()
      _send_pending()
```

**Comment by mfelsche** [comment]
I am a bit puzzled. In case of chunked response transfer-encoding, the http-parser should call `_deliver(payload)` on the `ClientConnection` which should shift the request from the `_sent` queue: https://github.com/ponylang/http/blob/master/http/_client_connection.pony#L124

It seems i need to debug using your test program.

**Comment by mfelsche** [comment]
I get it, the issue happens for `StreamTransfer` payloads, not for requests with `Transfer-Encoding: chunked`. `StreamTransfer` is currently broken. The place to fix this is mostly in the `HTTPParser`.

**Comment by aturley** [comment]
@mfelsche ah, thanks.

**Comment by mfelsche** [comment]
I am working on this, unless you want to tackle it @aturley .

**Comment by aturley** [comment]
@mfelsche I'll let you take it, but I'm curious to see what you come up with. I'll be poking around myself just to get a better idea of what's going on.

**Comment by mfelsche** [comment]
This condition [here](https://github.com/ponylang/http/blob/master/http/http_parser.pony#L214) doesn't catch the case for a `StreamTransfer` response (> 10000 bytes). Thus `HTTPHandler.apply(response)` is never called somehow, you will only receive chunks and never get to know the headers.

**Comment by aturley** [comment]
@mfelsche ah funny, I was wondering how the headers were supposed to get there if it was a chunked messages.
