### ISSUE TITLE
cannot build tests because net/ssl and regex are not part of the standard library

### ISSUE THREAD

**Issue by aturley** [ponylang/http#23]
## Description

The [net/ssl package](https://github.com/ponylang/ponyc/pull/3225) and [regex package](https://github.com/ponylang/ponyc/pull/3218) were recently removed from the standard library.

## Steps to reproduce

1. Install a version of `ponyc` commit b0b68f7a394ca6cd13198f2fdf7240bf7a116d8e.
2. build the `http` library using by running `make`.

## Expected behavior

The tests build and pass.

## Actual behavior

The tests fail to build with messages like "can't load package 'net/ssl'" and "can't load package 'regex'".

**Comment by mfelsche** [comment]
Thanks for this issue, yeah i am lagging behind compat with ponyc master. Gonna add the deps via `bundle.json`.

**Comment by aturley** [comment]
@mfelsche I've got a branch here with the changes, I can open a PR in a few minutes.

**Comment by mfelsche** [comment]
i would love to approve and merge said PR :)
