### ISSUE TITLE
HTTPServer closes the connection if the received chunk fails to parse

### ISSUE THREAD

**Issue by mfelsche** [ponylang/http#8]
Copied rom https://github.com/ponylang/ponyc/issues/2614 : 

Reported by @BlackYoup

----
I have a problem with the HTTP server where a long request URI would make the server close the connection even if the request is entirely valid. This is because the state machine doesn't seem to implement the "we need more information to decide" case, or at least I couldn't find it / may have not seen it.

## Reproduce
I can reproduce on both `0.21.3` and current master fb10149e116460f908f949310ff2876fe1a38688

I used the httpserver example with default options. I then made a request like this:
```
curl -v http://127.0.0.1:50000/testtesttesttesttesttesttesttesttesttesttesttestt
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 50000 (#0)
> GET /testtesttesttesttesttesttesttesttesttesttesttestt HTTP/1.1
> Host: 127.0.0.1:50000
> User-Agent: curl/7.59.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

If you remove the last `t` from the URI, it won't close the connection and proceed the request.

## Debug

I traced the problem up until here, into the `_ServerConnHandler.received()` method:
https://github.com/ponylang/ponyc/blob/fb10149e116460f908f949310ff2876fe1a38688/packages/net/http/_server_conn_handler.pony#L50...L74

If I print the output of the `data` variable when the first chunk comes in, it shows like this:
```
0x00: 4745 5420 2F74 6573 7474 6573 7474 6573  GET /testtesttes
0x10: 7474 6573 7474 6573 7474 6573 7474 6573  ttesttesttesttes
0x20: 7474 6573 7474 6573 7474 6573 7474 6573  ttesttesttesttes
0x30: 7474 6573 7474 2048 5454 502F 312E 310D  ttestt HTTP/1.1.
0x40:
```

As you can see, there is no line return (`\n`, `0xA`) at the end of the chunk, which comes in the next chunk we receive:
```
0x00: 0A48 6F73 743A 2031 3237 2E30 2E30 2E31  .Host: 127.0.0.1
0x10: 3A35 3030 3030 0D0A 5573 6572 2D41 6765  :50000..User-Age
0x20: 6E74 3A20 6375 726C 2F37 2E35 392E 300D  nt: curl/7.59.0.
0x30: 0A41 6363 6570 743A 202A 2F2A 0D0A 0D0A  .Accept: */*....
0x40:
```

But just that missing line return makes the `parse()` call fail and closes the connection.

I'm not sure how to fix this yet but given the amount of time I've put into that debug, I'd appreciate if you could give me a few insights as to how it could be fixed, if it's not too much work :)

**Comment by mfelsche** [comment]
My answer, also copied:

---
@BlackYoup Thanks for reporting this issue.

Your diagnosis is completely right.

The HTTP parser is trying to get a complete line from the [Reader](https://stdlib.ponylang.org/buffered-Reader) which fails with an `error`. See here: https://github.com/ponylang/ponyc/blob/master/packages/net/http/_http_parser.pony#L158

The way the `_ServerConnHandler` is calling the `HTTPParser` it is assuming that any error thrown in the `parse` method can be treated as a syntax error and thus the connection will be closed: https://github.com/ponylang/ponyc/blob/master/packages/net/http/_server_conn_handler.pony#L70

You just found one case where this kind of contract is violated. The parser should stay silent if not enough data is available. It will call the provided backend with the parsed request if available.

If we'd just wait until we have a newline and keep adding bytes we receive, i think the http server module will be subject to some easy ddos attack.
In this particular case it might be worth trying to parse the first line before we have a final line break so we can detect invalid requests early, and limiting the overall length of the initial buffer (before we have the first `\r\n`) to some value > 8000 bytes as recommended here: https://tools.ietf.org/html/rfc7230#section-3.1.1 .

If you want to start working on this, i would suggest adding a testcase with your request and start working on the method [_HTTPParser._parse_request](https://github.com/ponylang/ponyc/blob/master/packages/net/http/_http_parser.pony#L147).
But we are also glad to help out here.

As there is a pending RFC for removing the `net/http` package from the stdlib and make it a separate pony package, you could also start "forking" your version of `net/http` which would be a great start for getting this RFC going.

As you prefer.

**Comment by SeanTAllen** [comment]
@mfelsche can this be closed or does it need to be transferred?

**Comment by mfelsche** [comment]
can be closed. Is fixed.
